# Generated by Django 4.1.7 on 2023-03-31 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_remove_message_recipient_message_paper'),
    ]

    operations = [
        migrations.AddField(
            model_name='researchpaper',
            name='rating',
            field=models.IntegerField(default=0),
        ),
    ]
