# Generated by Django 4.1.7 on 2023-04-02 03:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0006_researchpaper_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='researchpaper',
            name='Authors',
        ),
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ResearchPaper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.researchpaper')),
                ('User', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
